# Generated by Django 4.0.6 on 2022-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
