# Generated by Django 4.0.6 on 2022-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
