# Generated by Django 4.0.6 on 2022-08-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author_slug',
        ),
    ]
