# Generated by Django 4.0.6 on 2022-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
