# Generated by Django 4.0.6 on 2022-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_description',
            field=models.TextField(default=None),
        ),
    ]
