# Generated by Django 4.0.6 on 2022-08-07 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_about_info_profile_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
