# Generated by Django 4.0.6 on 2022-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_about_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_description',
            field=models.TextField(max_length=90),
        ),
    ]
