# Generated by Django 4.0.6 on 2022-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_description',
            field=models.TextField(max_length=100),
        ),
    ]
