# Generated by Django 4.0.6 on 2022-08-07 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
