# Generated by Django 4.0.6 on 2022-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_profile_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
