# Generated by Django 4.0.6 on 2022-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='heading_img',
            field=models.ImageField(blank=True, default='article_heading/default.jpg', upload_to='article_heading'),
        ),
    ]
