# Generated by Django 4.0.6 on 2022-08-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_info',
            new_name='author_profile',
        ),
    ]
