# Generated by Django 4.0.6 on 2022-08-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_user_slug'),
        ('blog', '0014_rename_author_info_author_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
