# Generated by Django 4.0.6 on 2022-08-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_author_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
